#!/bin/bash
#SBATCH --time=2-00:00:00
#SBATCH --job-name=test
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=50gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=20
#SBATCH --nodes=1
srun python Run.py