#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=test
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=200gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --nodes=1
#SBATCH --exclude=xcne[0-5],xcng[0-1]
python Detect_language.py